export const userMessage = {
  VaLIDATION_ERROR: "Validation error",
  NAME_IS_REQUIRED: "Name is required",
  NAME_MUST_BE_STRING: "Name must be a string",
  NAME_LENGTH: "Name must be at least 3 characters long",
  EMAIL_ALREADY_EXISTS: "Email already exists",
  EMAIL_INVALID: "Email is invalid",
  Email_OR_PASSWORD_INCORRECT: "Email or password is incorrect",
  PASSWORD_IS_REQUIRED: "Password is required",
  PASSWORD_MUST_BE_STRING: "Password must be a string",
  PASSWORD_LENGTH: "Password must be at least 6 characters long",
  PASSWORD_MUST_BE_STRONG: "Password must contain at least one uppercase letter, one lowercase letter, one number, and one special character",
  CONFIRM_PASSWORD_IS_REQUIRED: "Confirm password is required",
  CONFIRM_PASSWORD_MUST_BE_STRING: "Confirm password must be a string",
  CONFIRM_PASSWORD_LENGTH: "Confirm password must be at least 6 characters long",
  CONFIRM_PASSWORD_MUST_BE_STRONG: "Confirm password must contain at least one uppercase letter, one lowercase letter, one number, and one special character",
  CONFIRM_PASSWORD_NOT_MATCH: "Confirm password not match the password",
  DATE_OF_BIRTH_IS_ISO8601: "Date of birth must be a valid ISO 8601 date",
  LOGIN_SUCCESS: "Login success",
  REGISTER_SUCCESS: "Register success",
  ACCESS_TOKEN_IS_REQUIRED: "Access token is required",
} as const